# Generated by Django 5.0.6 on 2024-05-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="image/default.jpg", upload_to="image"),
        ),
    ]
